## np.dot()のような関数を作成

In [2]:
import numpy as np

In [137]:
a =np.array([
    [1,2,3,4,5],
    [6,7,8,9,0],
    [4,9,7,8,9],
])

b = np.array([
    [1,6,4],
    [2,7,9],
    [3,8,7],
    [4,9,8],
    [5,0,9]
])

In [138]:
np.shape(a)

(3, 5)

In [139]:
np.shape(b)

(5, 3)

In [140]:
np.dot(a,b)

array([[ 55,  80, 120],
       [ 80, 230, 215],
       [120, 215, 291]])

In [141]:
q = np.arange(12)

In [142]:
q = q.reshape((3, 4))

In [143]:
q

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [144]:
a_0 = a.shape[0]
b_1 = b.shape[1]
ab = b.shape[0]

In [145]:
z = np.array([])

for y in range(a_0):
    for x in range(b_1):
        s = 0
        for i in range(ab):
            s += a[y][i]*b[i][x]
        z = np.append(z,s)
z = z.reshape((b_1, a_0))

In [146]:
z

array([[ 55.,  80., 120.],
       [ 80., 230., 215.],
       [120., 215., 291.]])

### 関数

In [147]:
def np_dot (a,b):
    z = np.array([])
    
    #引数が2次元配列でない場合
    if not a.ndim == 2 and b.ndim == 2:
        print('引数を2次元配列にしてください')
        return z
    #左の列数と右の行数が等しくない場合
    if not a.shape[1] == b.shape[0]:
        print('左の列数と右の行数が等しくありません')
        return z
    
    for y in range(a.shape[0]):
        for x in range(b.shape[1]):
            s = 0
            for i in range(b.shape[0]):
                s += a[y][i]*b[i][x]
            z = np.append(z,s)
    z = z.reshape(( a.shape[0],b.shape[1]))
    return z

In [148]:
np_dot(a,b)

array([[ 55.,  80., 120.],
       [ 80., 230., 215.],
       [120., 215., 291.]])

In [149]:
np.dot(a,b)

array([[ 55,  80, 120],
       [ 80, 230, 215],
       [120, 215, 291]])

In [150]:
a2 =np.array([
    [1,2,3,4,5],
    [6,7,8,9,0],
    [4,9,7,8,9],
])

b2 = np.array([
    [1,6,4,5],
    [2,7,9,7],
    [3,8,7,1],
    [4,9,8,0],
    [5,0,9,3]
])

In [151]:
np_dot(a2,b2)

array([[ 55.,  80., 120.,  37.],
       [ 80., 230., 215.,  87.],
       [120., 215., 291., 117.]])

In [152]:
np.dot(a2,b2)

array([[ 55,  80, 120,  37],
       [ 80, 230, 215,  87],
       [120, 215, 291, 117]])

In [153]:
a3 =np.array([
    [1,2,3,4,5],
    [6,7,8,9,0],
    [4,9,7,8,9]
])

b3 = np.array([
    [1,6,4,5],
    [2,7,9,7],
    [3,8,7,1],
    [4,9,8,0],
    [5,0,9,3],
    [5,0,9,3]
])

In [154]:
np_dot(a3,b3)

左の列数と右の行数が等しくありません


array([], dtype=float64)

In [155]:
a4 =np.array(
    [[
    [1,2,3,4,5],
    [6,7,8,9,0],
    [4,9,7,8,9]
    ],
     [
    [1,2,3,4,5],
    [6,7,8,9,0],
    [4,9,7,8,9]
    ]]
    )
a4.ndim

3

In [156]:
np_dot(a4,b)

引数を2次元配列にしてください


array([], dtype=float64)